org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Djavax.net.ssl.trustStoreType=WINDOWS-ROOT
systemProp.javax.net.ssl.trustStoreType=WINDOWS-ROOT
systemProp.org.gradle.internal.http.connectionTimeout=15000
systemProp.org.gradle.internal.http.socketTimeout=15000
android.useAndroidX=true
kotlin.incremental=false
